services:
  postgres-db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ${PWD}/postgres:/home/config
    command: [ 'postgres', '-c', 'config_file=/home/config/postgresql.conf' ]
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready', '-d', 'my_database' ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - kafka

networks:
  kafka:
    name: kafka
